# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron's Blog
tagline:          'Aaron Blog'
description:
url:              http://sol87.github.io/AaronHui
baseurl:          /

author:
  name:           'Aaron Hui'
  avatar:         /images/us.jpg
  email:          'guoliangxu1987@163.com'
  bio: "Who am I? I don't know either.Maybe I'm a coder? Or a thinker? Or a player? "


link_blogs:
  test: http://baidu.com


paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sol87/AaronHui
